### PR TITLE
First working version

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1)

### CODE REVIEW

**Comment by aledj2** [comment]
+@aledj2 

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @andyb3 and @aledj2)

---

*[Dockerfile, line 8 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvrYJN1vsd7KGa16A-:-LFvrYJN1vsd7KGa16A0:b-9mrqsy) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/Dockerfile#L8)):*
> ```Dockerfile
> 
> # Install Ubuntu dependencies
> RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y wget apt-transport-https
> ```

Do need to specify version no? This applies to all of the steps in this file 

---

*[src/albacore_1D_barcoded.sh, line 16 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvt6sL4CUy29_EQMH5:-LFvt6sL4CUy29_EQMH6:b-unu9nq) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L16)):*
> ```Shell
> mkdir -p $HOME/albacore_output $HOME/out/fastq_files $HOME/out/albacore_output_all
> 
> # Run Albacore
> ```

Majority of the below args are self explanatory but could you add a quick explanation of the more obscure such as reads per fastq batch and barcoding please 

---

*[src/albacore_1D_barcoded.sh, line 19 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvsps735CmkCZUKbM_:-LFvsps735CmkCZUKbMa:bubvu9p) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L19)):*
> ```Shell
> dx-docker run -v $HOME:/data mokaguys/albacore:v2.2 read_fast5_basecaller.py \
>     --input /data/ \
>     --worker_threads 11 \
> ```

Is it worth calculating the number of available cores and using that here? Looks like instance type only has 8 cores? 

---

*[src/albacore_1D_barcoded.sh, line 36 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvth3uDUWAxCThq1w_:-LFvth3uDUWAxCThq1wa:b-ookwpl) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L36)):*
> ```Shell
> reached_data_section=false
> # Read through samplesheet line by line
> while read samplesheet_line; do
> ```

Is samplesheet _line a helper variable? 

---

*[src/albacore_1D_barcoded.sh, line 43 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvuPwj1ls2ysnzkh2E:-LFvuPwj1ls2ysnzkh2F:beixpw1) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L43)):*
> ```Shell
>         barcode=$(echo $samplesheet_line | cut -d ',' -f5)
>         # Check file exists
>         if [ -f $HOME/albacore_output/workspace/pass/${barcode}/*.fastq ]; then
> ```

What if it doesn't exist? 

---

*[src/albacore_1D_barcoded.sh, line 46 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvu7izENyHJakOqpf6:-LFvu7izENyHJakOqpf7:b-hix5db) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L46)):*
> ```Shell
>             # Copy the fastq from the matching barcode folder in albacore output, and rename using the sample name 
>             cp $HOME/albacore_output/workspace/pass/${barcode}/*.fastq $HOME/out/fastq_files/${sample_name}.fastq
>             # Gzip the fastq.
> ```

Does copying mean there is a unzipped fastq with old name in albacore output? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-:-LFvrNNY5Jc7BbGqCf1U:bweg3f8)*

**Comment by andyb3** [comment]
Review status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @andyb3 and @aledj2)

---

*[Dockerfile, line 8 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvrYJN1vsd7KGa16A-:-LFwCk53-ZXKEQtPHTvz:b69uf3a) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/Dockerfile#L8)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Do need to specify version no? This applies to all of the steps in this file 
</blockquote></details>

This file is based on the albacore installation instructions from ONT, in which they don't specify version numbers for the dependencies. The dockerfile is only used once on the initial build. The built image is then cached in DNAnexus and used by the app, so the versions of these dependencies will always be the same between runs. I just stuck the dockerfile in as a record of how the docker image was built. If you re-ran this dockerfile today it would fail because the version of Albacore used here has already been superseded and this version is no longer available at the link in the file!!

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1)*

**Comment by andyb3** [comment]
Review status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @aledj2 and @andyb3)

---

*[src/albacore_1D_barcoded.sh, line 19 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvsps735CmkCZUKbM_:-LFwGlq4B9yRbWH3qrEl:b220xrj) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L19)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Is it worth calculating the number of available cores and using that here? Looks like instance type only has 8 cores? 
</blockquote></details>

I followed this guide from ONT for calculating threads


---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1)*

**Comment by andyb3** [comment]
*[src/albacore_1D_barcoded.sh, line 19 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvsps735CmkCZUKbM_:-LFwHRD18aQu0OTV7qsc:bpmkzkc) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L19)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

I followed this guide from ONT for calculating threads


</blockquote></details>

I'm not sure if that guide assumes hyperthreading so each core can have 2 threads, but giving 11 threads seems to work in testing so will leave as is for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1)*

**Comment by andyb3** [comment]
Review status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @aledj2 and @andyb3)

---

*[src/albacore_1D_barcoded.sh, line 16 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvt6sL4CUy29_EQMH5:-LFwICkcDyfpN53Ur4oK:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L16)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Majority of the below args are self explanatory but could you add a quick explanation of the more obscure such as reads per fastq batch and barcoding please 
</blockquote></details>

Done.

---

*[src/albacore_1D_barcoded.sh, line 36 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvth3uDUWAxCThq1w_:-LFwIzUkCzM4fTJd9qCC:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L36)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Is samplesheet _line a helper variable? 
</blockquote></details>

Done.

---

*[src/albacore_1D_barcoded.sh, line 46 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvu7izENyHJakOqpf6:-LFwKiPX0kFfTt7ARD-5:bes712i) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L46)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Does copying mean there is a unzipped fastq with old name in albacore output? 
</blockquote></details>

Yes, idea is to upload named fastqs individually, but also upload the full unmodified albacore output for our records 

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1)*

**Comment by andyb3** [comment]
Review status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @aledj2 and @andyb3)

---

*[src/albacore_1D_barcoded.sh, line 43 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvuPwj1ls2ysnzkh2E:-LFwLR2H0z6MwWfqrC3B:b8ecfz9) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L43)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

What if it doesn't exist? 
</blockquote></details>

The file should always be there. But Albacore sometimes takes several hours to run so I didn't want the whole app to fail if it can't find one of the fastq files. This would be picked up downstream if a file was missing. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1)*

**Comment by aledj2** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[src/albacore_1D_barcoded.sh, line 36 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvth3uDUWAxCThq1w_:-LFwOFBg22CLTVCvGnE5:b-u8aqr4) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L36)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK! $samplesheet_path fed into end of the command

---

*[src/albacore_1D_barcoded.sh, line 43 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-LFvuPwj1ls2ysnzkh2E:-LFwOOYq1cGbihls1FaF:blo1s15) ([raw file](https://github.com/moka-guys/dnanexus_albacore_barcoding/blob/2432e1d8fd65050e78bb9ae149f670b03e928423/src/albacore_1D_barcoded.sh#L43)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

The file should always be there. But Albacore sometimes takes several hours to run so I didn't want the whole app to fail if it can't find one of the fastq files. This would be picked up downstream if a file was missing. 
</blockquote></details>

OK! The check is to make sure the file exists, not that it exists in the destination

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_albacore_barcoding/1#-:-LFwOgXdAl1496NhMP7F:bnfp4nl)*

**Pull request merged**
